# Generated by Django 4.2.3 on 2024-01-02 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmd_basesdatos_t',
            fields=[
                ('id_bd', models.AutoField(primary_key=True, serialize=False)),
                ('cod_bd', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True)),
                ('tipo_bd', models.CharField(choices=[('1', 'Under 09s'), ('2', 'Under 10s'), ('3', 'Under 11s')], max_length=30, null=True)),
                ('bd_default', models.CharField(max_length=1, null=True)),
                ('fec_creacion', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 11, 41, 13, 568872), null=True)),
                ('usu_creacion', models.CharField(max_length=30, null=True)),
                ('ip_equipo', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
